language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
env:
  global:
    - COVERALLS_PARALLEL=true
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # create environment and install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coverage coveralls
  - source activate test-environment
  - conda env update -n test-environment -f environment.yml
  - pip install --user git+https://github.com/matplotlib/basemap.git # workaround
  - pip install .

before_script:
  - "export MPLBACKEND=agg"

script:
  - nosetests uvtools --with-coverage --cover-package=uvtools
after_success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
